###
GET http://localhost:3000/alumnos HTTP/1.1
###
POST http://localhost:3000/alumnos HTTP/1.1
Content-Type: application/json

{
    "first_name": "juan",
    "last_name": "lucas",
    "email": "juanlucas@test.com",
    "phone": "1851223",
    "address": "midomicilio 420"

}

###
PUT http://localhost:3000/alumnos/3 HTTP/1.1
Content-Type: application/json

 {
     
        "first_name": "juan",
        "last_name": "lucas",
        "email": "juanlucasbiain@test.com",
        "phone": "1851223",
        "address": "midomicilio 420"
      }

###
DELETE http://localhost:3000/alumnos/1 HTTP/1.1


